jobs:
- deployment: ${{ parameters.jobName }}
  environment: ${{ parameters.environment }}
  variables:
  - group: ${{ parameters.variableGroupName }}
  strategy:
    runOnce:
      deploy:
        steps:
        - download: current
          artifact: drop

        - task: AzureAppServiceSettings@1
          displayName: 'Azure App Service Settings'
          inputs:
            azureSubscription: $(ServiceConnectionName)
            appName: '${{ parameters.appName }}'
            appSettings: >
              [
                {
                  "name": "MESSAGE",
                  "value": "${{ parameters.message }}",
                  "slotSetting": false
                }
              ]

        - task: AzureWebApp@1
          displayName: 'Azure App Service Deploy: website'
          inputs:
            azureSubscription: $(ServiceConnectionName)
            appType: 'webAppLinux'
            appName: '${{ parameters.appName }}'
            package: '$(Pipeline.Workspace)/drop/$(buildConfiguration)/*.zip'
